name: Development Builds
on:
  push:
    branches: [develop]
  pull_request:
    branches: [develop]
    branches-ignore: ['analysis*', 'dependabot/*']
env:
  CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
jobs:
  coverage:
    name: CodeCov coverage reports
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v5
        with:
          fetch-depth: 0
      - name: Set up Python 3.11
        uses: actions/setup-python@v3
        with:
          python-version: 3.11
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -U pytest pytest-cov
      - name: Test with pytest
        run: |
          pytest --cov=. --cov-report=xml --cov-report=term-missing \
           --junitxml=junit.xml -o junit_family=legacy
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v5
        with:
          token: ${{ env.CODECOV_TOKEN }}
          files: ./coverage.xml
      - name: Upload test results to Codecov
        if: ${{ !cancelled() }}
        uses: codecov/test-results-action@v1
        with:
          token: ${{ env.CODECOV_TOKEN }}
