name: Production Build
on:
  push:
    branches:
      - 'main'
  pull_request:
    branches:
      - 'main'
env:
  CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
jobs:
  coverage:
    name: CodeCov coverage reports
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source code
        uses: actions/checkout@v5
        with:
          fetch-depth: 0
      - name: Setup Bun package manager
        uses: oven-sh/setup-bun@v2
        with:
          bun-version-file: ".bun-version"
      - name: Install dependencies
        run: bun install --frozen-lockfile
      - name: Run tests with coverage
        run: bun run test:coverage
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v5
        with:
          token: ${{ env.CODECOV_TOKEN }}
          files: ./coverage/lcov.info
          flags: tests
          verbose: false
          fail_ci_if_error: false
      - name: Upload test results to Codecov
        if: ${{ !cancelled() }}
        uses: codecov/test-results-action@v1
        with:
          token: ${{ env.CODECOV_TOKEN }}
          files: junit.xml
